on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: remodietlicher/hello-world-composite-action@v3
        with:
          who-to-greet: 'Mona the Octocattt'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: cat hello.txt
        shell: bash
      - run: echo $HELLO
        shell: bash
